name = "sos25-client"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-04-19"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NEXT_PUBLIC_API_ENDPOINT = "https://sos24-api-stg.playground.sohosai.com"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCSv4uZ8jipdGwagzp7fzejucbHjEp8Hrw"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:592763755647:web:d7f0831540b85e5da4334a"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "sos24-dev.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "592763755647"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "sos24-dev"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "sos24-dev.appspot.com"

[env.production]
compatibility_date = "2024-11-11"

[env.production.vars]
NEXT_PUBLIC_API_ENDPOINT = "https://sos25api.sohosai.com"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDqR2HzALh0rzFDk1ylmSFynPB8hmH8vlo"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:443590530491:web:5bd6bc563676bf2c47609e"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "sos25-main.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "443590530491"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "sos25-main"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "sos25-main.appspot.com"
NEXT_PUBLIC_GTMID = "GTM-MG7FD288"
NEXT_PUBLIC_SENTRY_DSN = "https://46644e4ad167a3a09182716f44bc953d@o4507113970466816.ingest.us.sentry.io/4507114421747712"
NEXT_PUBLIC_SENTRY_PROJECT = "sos24-client-prod"
