import { components } from "@/schema";
import { uuidV4 } from "./helper";

export const testFormSummaries: components["schemas"]["FormSummary"][] = [
  {
    answer_id: uuidV4(),
    answered_at: "2023-09-15T10:20:30Z",
    attributes: ["academic", "official", "inside"],
    categories: ["general", "stage_university_hall"],
    description:
      "これは大学の学術イベントの申請フォームです。このイベントでは、最新の研究成果を発表し、学術的な議論を行います。",
    ends_at: "2023-11-30T18:00:00Z",
    id: uuidV4(),
    starts_at: "2023-11-30T09:00:00Z",
    title: "大学学術イベント",
    updated_at: "2023-09-15T10:20:30Z",
  },
  {
    answer_id: uuidV4(),
    answered_at: "2023-08-10T14:45:00Z",
    attributes: ["art", "outside"],
    categories: ["foods_with_kitchen", "stage_united"],
    description: "これは地域の夏祭りの申請フォームです。祭りでは、地元の食べ物や音楽、ダンスなどが楽しめます。",
    ends_at: "2023-08-20T22:00:00Z",
    id: uuidV4(),
    starts_at: "2023-08-20T10:00:00Z",
    title: "地域夏祭り",
    updated_at: "2023-08-10T14:45:00Z",
  },
  {
    answer_id: uuidV4(),
    answered_at: "2023-07-01T09:30:00Z",
    attributes: ["official", "inside"],
    categories: ["foods_without_kitchen", "stage_1a"],
    description:
      "これは企業の研修ワークショップの申請フォームです。このワークショップでは、チームビルディングとスキル向上を目指します。",
    ends_at: "2023-07-15T17:00:00Z",
    id: uuidV4(),
    starts_at: "2023-07-15T09:00:00Z",
    title: "企業研修ワークショップ",
    updated_at: "2023-07-01T09:30:00Z",
  },
  {
    answer_id: uuidV4(),
    answered_at: "2023-06-20T11:15:00Z",
    attributes: ["academic", "official", "inside"],
    categories: ["general", "stage_university_hall"],
    description:
      "これは国際学術会議の申請フォームです。この会議では、世界中の研究者が集まり、最新の研究成果を発表します。",
    ends_at: "2023-09-01T18:00:00Z",
    id: uuidV4(),
    starts_at: "2023-09-01T09:00:00Z",
    title: "国際学術会議",
    updated_at: "2023-06-20T11:15:00Z",
  },
  {
    answer_id: uuidV4(),
    answered_at: "2023-05-05T08:00:00Z",
    attributes: ["academic", "inside"],
    categories: ["general", "stage_university_hall"],
    description:
      "これは地域の住民会議の申請フォームです。この会議では、地域の問題について話し合い、解決策を見つけます。",
    ends_at: "2023-05-10T12:00:00Z",
    id: uuidV4(),
    starts_at: "2023-05-10T09:00:00Z",
    title: "地域住民会議",
    updated_at: "2023-05-05T08:00:00Z",
  },
];

export const testFormItems: components["schemas"]["FormItem"][] = [
  {
    id: uuidV4(),
    name: "テキスト",
    description: "テキストの説明です",
    required: true,
    type: "string",
    min_length: null,
    max_length: null,
    allow_newline: false,
  },
  {
    id: uuidV4(),
    name: "テキストエリア",
    description: "テキストエリアの説明です",
    required: true,
    type: "string",
    min_length: null,
    max_length: null,
    allow_newline: true,
  },
  {
    id: uuidV4(),
    name: "数値",
    description: "数値項目の説明です",
    required: true,
    type: "int",
    min: null,
    max: null,
  },
  {
    id: uuidV4(),
    name: "チェックボックス",
    description: "チェックボックスの説明です",
    required: true,
    type: "choose_many",
    options: ["選択0", "選択1", "洗濯"],
    min_selection: null,
    max_selection: null,
  },
  {
    id: uuidV4(),
    name: "ドロップダウン",
    description: "ドロップダウンの説明です",
    required: true,
    type: "choose_one",
    options: [
      "いろはにほへと",
      "ちりぬるを",
      "わかよたれそ",
      "つねならむ",
      "ういのおくやま",
      "けふこえて",
      "あさきゆめみし",
      "ゑひもせす",
    ],
  },
];

export const testForm: components["schemas"]["Form"] = {
  id: uuidV4(),
  title: "全項目",
  description: "全項目を追加するテスト",
  starts_at: "2023-12-31T15:00:00+00:00",
  ends_at: "2024-05-01T14:59:00+00:00",
  categories: [
    "general",
    "foods_with_kitchen",
    "foods_without_kitchen",
    "foods_without_cooking",
    "stage_1a",
    "stage_university_hall",
    "stage_united",
  ],
  attributes: ["academic", "art", "official", "inside", "outside"],
  items: [
    {
      id: uuidV4(),
      name: "テキスト",
      description: "テキストの説明です",
      required: true,
      type: "string",
      min_length: null,
      max_length: null,
      allow_newline: false,
    },
    {
      id: uuidV4(),
      name: "テキストエリア",
      description: "テキストエリアの説明です",
      required: true,
      type: "string",
      min_length: null,
      max_length: null,
      allow_newline: true,
    },
    {
      id: uuidV4(),
      name: "数値",
      description: "数値項目の説明です",
      required: true,
      type: "int",
      min: null,
      max: null,
    },
    {
      id: uuidV4(),
      name: "チェックボックス",
      description: "チェックボックスの説明です",
      required: true,
      type: "choose_many",
      options: ["選択0", "選択1", "洗濯"],
      min_selection: null,
      max_selection: null,
    },
    {
      id: uuidV4(),
      name: "ドロップダウン",
      description: "ドロップダウンの説明です",
      required: true,
      type: "choose_one",
      options: [
        "いろはにほへと",
        "ちりぬるを",
        "わかよたれそ",
        "つねならむ",
        "ういのおくやま",
        "けふこえて",
        "あさきゆめみし",
        "ゑひもせす",
      ],
    },
    {
      id: uuidV4(),
      name: "ファイル",
      description: "ファイルをアップロードしてね！拡張子はjpgかpng、2枚までだよ",
      required: true,
      type: "file",
      extensions: [".jpg", ".png"],
      limit: 2,
    },
  ],
  attachments: [],
  answer_id: null,
  answered_at: null,
  created_at: "2024-04-21T22:58:23.678006256+00:00",
  updated_at: "2024-04-21T23:33:59.097885666+00:00",
};

export const testAnswer = ({
  projectTitle = "企画名",
  createdAt = "2024-04-21T23:36:51.015124334+00:00",
  updatedAt = "2024-05-19T05:36:26.307030404+00:00",
}): components["schemas"]["FormAnswer"] => ({
  id: uuidV4(),
  project_id: uuidV4(),
  project_title: projectTitle,
  form_id: uuidV4(),
  form_title: "全項目",
  items: [
    {
      type: "string",
      item_id: uuidV4(),
      value: "テスト",
    },
    {
      type: "string",
      item_id: uuidV4(),
      value: "てすと",
    },
    {
      type: "int",
      item_id: uuidV4(),
      value: 3,
    },
    {
      type: "choose_many",
      item_id: uuidV4(),
      value: ["洗濯", "選択1"],
    },
    {
      type: "choose_one",
      item_id: uuidV4(),
      value: "わかよたれそ",
    },
    {
      type: "file",
      item_id: uuidV4(),
      value: [uuidV4()],
    },
  ],
  created_at: createdAt,
  updated_at: updatedAt,
});
