import { components } from "@/schema";
import { uuidV4 } from "./helper";

export const testFormItems: components["schemas"]["FormItem"][] = [
  {
    id: uuidV4(),
    name: "テキスト",
    description: "テキストの説明です",
    required: true,
    type: "string",
    min_length: null,
    max_length: null,
    allow_newline: false,
  },
  {
    id: uuidV4(),
    name: "テキストエリア",
    description: "テキストエリアの説明です",
    required: true,
    type: "string",
    min_length: null,
    max_length: null,
    allow_newline: true,
  },
  {
    id: uuidV4(),
    name: "数値",
    description: "数値項目の説明です",
    required: true,
    type: "int",
    min: null,
    max: null,
  },
  {
    id: uuidV4(),
    name: "チェックボックス",
    description: "チェックボックスの説明です",
    required: true,
    type: "choose_many",
    options: ["選択0", "選択1", "洗濯"],
    min_selection: null,
    max_selection: null,
  },
  {
    id: uuidV4(),
    name: "ドロップダウン",
    description: "ドロップダウンの説明です",
    required: true,
    type: "choose_one",
    options: [
      "いろはにほへと",
      "ちりぬるを",
      "わかよたれそ",
      "つねならむ",
      "ういのおくやま",
      "けふこえて",
      "あさきゆめみし",
      "ゑひもせす",
    ],
  },
];

export const testForm: components["schemas"]["Form"] = {
  id: uuidV4(),
  title: "全項目",
  description: "全項目を追加するテスト",
  starts_at: "2023-12-31T15:00:00+00:00",
  ends_at: "2024-05-01T14:59:00+00:00",
  is_draft: true,
  categories: [
    "general",
    "foods_with_kitchen",
    "foods_without_kitchen",
    "foods_without_cooking",
    "stage_1a",
    "stage_university_hall",
    "stage_united",
  ],
  attributes: ["academic", "art", "official", "inside", "outside"],
  items: [
    {
      id: uuidV4(),
      name: "テキスト",
      description: "テキストの説明です",
      required: true,
      type: "string",
      min_length: null,
      max_length: null,
      allow_newline: false,
    },
    {
      id: uuidV4(),
      name: "テキストエリア",
      description: "テキストエリアの説明です",
      required: true,
      type: "string",
      min_length: null,
      max_length: null,
      allow_newline: true,
    },
    {
      id: uuidV4(),
      name: "数値",
      description: "数値項目の説明です",
      required: true,
      type: "int",
      min: null,
      max: null,
    },
    {
      id: uuidV4(),
      name: "チェックボックス",
      description: "チェックボックスの説明です",
      required: true,
      type: "choose_many",
      options: ["選択0", "選択1", "洗濯"],
      min_selection: null,
      max_selection: null,
    },
    {
      id: uuidV4(),
      name: "ドロップダウン",
      description: "ドロップダウンの説明です",
      required: true,
      type: "choose_one",
      options: [
        "いろはにほへと",
        "ちりぬるを",
        "わかよたれそ",
        "つねならむ",
        "ういのおくやま",
        "けふこえて",
        "あさきゆめみし",
        "ゑひもせす",
      ],
    },
    {
      id: uuidV4(),
      name: "ファイル",
      description: "ファイルをアップロードしてね！拡張子はjpgかpng、2枚までだよ",
      required: true,
      type: "file",
      extensions: [".jpg", ".png"],
      limit: 2,
    },
  ],
  attachments: [],
  answer_id: null,
  answered_at: null,
  created_at: "2024-04-21T22:58:23.678006256+00:00",
  updated_at: "2024-04-21T23:33:59.097885666+00:00",
};

export const testAnswer: components["schemas"]["FormAnswer"] = {
  id: uuidV4(),
  project_id: uuidV4(),
  project_title: "企画名",
  form_id: uuidV4(),
  form_title: "全項目",
  items: [
    {
      type: "string",
      item_id: uuidV4(),
      value: "テスト",
    },
    {
      type: "string",
      item_id: uuidV4(),
      value: "てすと",
    },
    {
      type: "int",
      item_id: uuidV4(),
      value: 3,
    },
    {
      type: "choose_many",
      item_id: uuidV4(),
      value: ["洗濯", "選択1"],
    },
    {
      type: "choose_one",
      item_id: uuidV4(),
      value: "わかよたれそ",
    },
    {
      type: "file",
      item_id: uuidV4(),
      value: [uuidV4()],
    },
  ],
  created_at: "2024-04-21T23:36:51.015124334+00:00",
  updated_at: "2024-05-19T05:36:26.307030404+00:00",
};
