name: CD(beta)
run-name: CD (beta) - ${{ github.event_name }}

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:

env:
  PROJECT_NAME: ${{ vars.CLOUDFLARE_BETA_PROJECT_NAME }}
  PRODUCTION_BRANCH: develop

jobs:
  build_and_deploy:
    if: |
      github.event.pull_request.merged == true ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Symlink
        run: |
          mkdir -p /home/runner/work/${{ github.event.repository.name }}/
          ln -s ${{ github.workspace }} /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - name: cache
        uses: actions/cache@v4
        with:
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ~/.npm
            /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.next/cache
            node_modules
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - run: ls -la && npm ci
      - name: build
        id: build
        run: npx @cloudflare/next-on-pages@1
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{vars.BETA_API_ENDPOINT}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{vars.BETA_FIREBASE_API_KEY}}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{vars.BETA_FIREBASE_APP_ID}}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{vars.BETA_FIREBASE_AUTH_DOMAIN}}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{vars.BETA_FIREBASE_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{vars.BETA_FIREBASE_PROJECT_ID}}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{vars.BETA_FIREBASE_STORAGE_BUCKET}}
          NEXT_PUBLIC_SENTRY_DSN: ${{vars.SENTRY_DSN}}
          NEXT_PUBLIC_SENTRY_PROJECT: ${{vars.SENTRY_PROJECT}}
      - name: deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        if: steps.build.outcome == 'success'
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
          accountId: ${{vars.CLOUDFLARE_ACCOUNT_ID}}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: |
            pages project list
            pages deploy .vercel/output/static --project-name=${{ env.PROJECT_NAME }} --branch=develop
      - name: Sentry
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
      - name: Notify
        uses: sarisia/actions-status-discord@v1
        if: always() && !cancelled()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "status: ${{ job.status }} \n🔗 Preview URL: ${{ steps.publish.outputs.deployment-url }}"
          title: "${{ github.workflow }}"
          description: "Build and deploy status of sos24-client-beta."
          color: 0x6600CC
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: GitHub Actions
          avatar_url: https://r2.sohosai.com/logo.png
